spring.application.name=budzetly-backend
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.viqknkkffaooglnhagoi
spring.datasource.password=Budzetly@575

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=budzetly-secret-key-budzetly-secret-key-123456
jwt.expiration=86400000